const actionTypes = {
  GET_MOVIE_LIST: "GET_MOVIE_LIST",
  GET_MOVIE_LIST_REQUEST: "GET_MOVIE_LIST_REQUEST",
  GET_MOVIE_LIST_FAILURE: "GET_MOVIE_LIST_FAILURE",
  GET_MOVIE_LIST_DETAIL: "GET_MOVIE_LIST_DETAIL",
  GET_MOVIE_LIST_DETAIL_REQUEST: "GET_MOVIE_LIST_DETAIL_REQUEST",
  GET_MOVIE_LIST_DETAIL_FAILURE: "GET_MOVIE_LIST_DETAIL_FAILURE"
};

export default actionTypes;
